### ISSUE TITLE
Block color changing very slightly - Looks normal in hotbar

### ISSUE THREAD

**Issue by flytrapcodes** [SeafoamWolf/SeafoamsDyeableBlocks#9]
![image](https://user-images.githubusercontent.com/88637604/232360388-47fd5dc9-116a-44f8-ae82-e431e50d6071.jpg)
The block in my hotbar is the exact same block placed down, but for some reason the color is barely different from the plain white block. Is this potentially an issue with my lighting settings?

**Comment by flytrapcodes** [comment]
Small update- I turned on/off smooth lighting and other settings and this seemed to have made no difference. I did notice that when placing blocks next to one another there seems to be a slight gradiant towards the middle.

**Comment by J-K-Tech** [comment]
same

**Comment by J-K-Tech** [comment]
update: disable sodium

**Comment by SeafoamWolf** [comment]
Yeah, unfortunately Sodium messes with the way that biome blending is handled. It sort of messes up the coloring of the dyed blocks since it uses that too. You can either turn Biome Blending in the settings all the way down, or just not use Sodium.
I wish there was a better solution, but I haven't been able to find one yet.
